name: Build iOS (native, like CI_Core)
"on": { workflow_dispatch: {} }

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: false

      - name: Prepare bundler
        run: |
          gem install bundler -v 2.7.2
          bundle config set path 'vendor/bundle'
          bundle config set deployment 'true'
          bundle config set without 'development test'
          bundle --version

      - name: Add Bundler platforms (macOS runners)
        run: |
          bundle lock --add-platform arm64-darwin-24
          bundle lock --add-platform x86_64-darwin-23
          bundle lock --add-platform ruby || true

      - name: Install Ruby gems
        run: |
          bundle install --jobs 4 --retry 3 --verbose

      - name: Use MATCH_DEPLOY_KEY (if present)
        if: ${{ secrets.MATCH_DEPLOY_KEY != '' }}
        shell: bash
        env:
          MATCH_DEPLOY_KEY: ${{ secrets.MATCH_DEPLOY_KEY }}
        run: |
          set -euo pipefail
          eval "$(ssh-agent -s)"
          printf '%s' "${MATCH_DEPLOY_KEY}" | sed 's/\\n/\n/g' | tr -d '\r' | ssh-add -
          mkdir -p ~/.ssh
          printf "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

      - name: Build + Upload (Fastlane)
        env:
          APPSTORE_ISSUER_ID: ${{ secrets.APPSTORE_ISSUER_ID }}
          APPSTORE_KEY_ID:     ${{ secrets.APPSTORE_KEY_ID }}
          APPSTORE_P8:         ${{ secrets.APPSTORE_P8 }}
          GH_PAT:              ${{ secrets.GH_PAT }}
          GITHUB_REPOSITORY:   ${{ github.repository }}
          MATCH_REPOSITORY:    ${{ secrets.MATCH_REPOSITORY }}
          MATCH_PASSWORD:      ${{ secrets.MATCH_PASSWORD }}
          MATCH_GIT_BRANCH:    main
          IOS_BUNDLE_ID:       ${{ secrets.IOS_BUNDLE_ID }}
          PROJECT_NAME:        ${{ secrets.PROJECT_NAME }}
          IOS_SCHEME:          ${{ secrets.IOS_SCHEME }}
        run: |
          bundle exec fastlane ios init_ci
