name: Build iOS (Pods + Fastlane)
"on": { workflow_dispatch: {} }

jobs:
  build:
    runs-on: macos-latest

    steps:
      # 1️⃣ Клонируем репозиторий
      - uses: actions/checkout@v4

      # 2️⃣ Устанавливаем Ruby и Bundler
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: false

      - name: Prepare bundler (arm64-safe)
        run: |
          gem install bundler -v 2.7.2
          bundle config set path 'vendor/bundle'
          bundle config set deployment 'true'
          bundle config set without 'development test'
          bundle --version

      # 3️⃣ Устанавливаем Ruby-зависимости
      - name: Install Ruby gems
        run: |
          bundle install --jobs 4 --retry 3 --verbose | tee bundle_install.log

      # 4️⃣ Кешируем Pods для ускорения сборки
      - name: Cache CocoaPods
        uses: actions/cache@v4
        with:
          path: |
            ~/.cocoapods
            Pods
            **/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      # 5️⃣ Устанавливаем зависимости через Podfile
      - name: Install CocoaPods dependencies
        shell: bash
        run: |
          set -euo pipefail
          # Ищем Podfile
          if [[ -f "Podfile" ]]; then
            POD_DIR="."
          elif [[ -f "ios/Podfile" ]]; then
            POD_DIR="ios"
          else
            echo "⚠️ Podfile не найден, пропускаем установку."
            exit 0
          fi
          echo "📦 Используем Podfile в: $POD_DIR"
          pushd "$POD_DIR" >/dev/null
          bundle exec pod install --repo-update --verbose
          popd >/dev/null

      # 6️⃣ Проверяем, что появился .xcworkspace
      - name: Verify Xcode workspace (after pods)
        shell: bash
        run: |
          set -euo pipefail
          WS=$(ls -1 *.xcworkspace 2>/dev/null || true)
          if [[ -z "$WS" ]]; then
            WS=$(ls -1 ios/*.xcworkspace 2>/dev/null || true)
          fi
          if [[ -z "$WS" ]]; then
            echo "❌ Не найден .xcworkspace — pods не создали воркспейс."
            exit 1
          fi
          echo "✅ Найден workspace:"
          echo "$WS"

      # 7️⃣ Сборка и публикация через Fastlane
      - name: Build + Upload (init_ci has fallback inside)
        env:
          APPSTORE_ISSUER_ID: ${{ secrets.APPSTORE_ISSUER_ID }}
          APPSTORE_KEY_ID:     ${{ secrets.APPSTORE_KEY_ID }}
          APPSTORE_P8:         ${{ secrets.APPSTORE_P8 }}
          IOS_BUNDLE_ID:       ${{ secrets.IOS_BUNDLE_ID }}
          MATCH_GIT_URL:       https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ secrets.MATCH_REPOSITORY }}.git
          MATCH_GIT_BRANCH:    main
          MATCH_PASSWORD:      ${{ secrets.MATCH_PASSWORD }}
          PROJECT_NAME:        ${{ secrets.PROJECT_NAME }}
          IOS_SCHEME:          ${{ secrets.IOS_SCHEME }}
        run: bundle exec fastlane ios init_ci
