name: Build iOS
"on": { workflow_dispatch: {} }

jobs:
  build:
    runs-on: macos-latest

    steps:
      # 1) Checkout
      - uses: actions/checkout@v4

      # 2) Setup Ruby
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: false

      - name: Prepare bundler
        run: |
          gem install bundler -v 2.7.2
          bundle config set path 'vendor/bundle'
          bundle config set deployment 'true'
          bundle config set without 'development test'
          bundle --version

      # Optional but fixes arm64-darwin platform lock issues on macOS runners
      - name: Add Bundler platforms (macOS runners)
        run: |
          bundle lock --add-platform arm64-darwin-24
          bundle lock --add-platform x86_64-darwin-23
          bundle lock --add-platform ruby || true

      - name: Install Ruby gems
        run: |
          bundle install --jobs 4 --retry 3 --verbose | tee bundle_install.log

      # 3) SSH key for match repo (parity with CI_Core which uses deploy key)
      - name: Setup SSH for match repo
        shell: bash
        env:
          MATCH_DEPLOY_KEY: ${{ secrets.MATCH_DEPLOY_KEY }}
        run: |
          set -euo pipefail
          mkdir -p ~/.ssh
          echo "${MATCH_DEPLOY_KEY}" > ~/.ssh/match_deploy_key
          chmod 600 ~/.ssh/match_deploy_key
          ssh-agent -s > agent.env
          source agent.env
          ssh-add ~/.ssh/match_deploy_key
          printf "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

      # 4) Build & upload via Fastlane (pods handled inside Fastlane as in CI_Core)
      - name: Build iOS with Fastlane
        env:
          APPSTORE_ISSUER_ID: ${{ secrets.APPSTORE_ISSUER_ID }}
          APPSTORE_KEY_ID:     ${{ secrets.APPSTORE_KEY_ID }}
          APPSTORE_P8:         ${{ secrets.APPSTORE_P8 }}

          GH_PAT:              ${{ secrets.GH_PAT }}
          GITHUB_REPOSITORY:   ${{ github.repository }}
          MATCH_REPOSITORY:    ${{ secrets.MATCH_REPOSITORY }}
          MATCH_PASSWORD:      ${{ secrets.MATCH_PASSWORD }}

          IOS_BUNDLE_ID:       ${{ secrets.IOS_BUNDLE_ID }}
          PROJECT_NAME:        ${{ secrets.PROJECT_NAME }}
          IOS_SCHEME:          ${{ secrets.IOS_SCHEME }}
        run: |
          bundle exec fastlane ios init_ci
