name: Build iOS (native)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: false

      - name: Prepare bundler
        run: |
          gem install bundler -v 2.7.2
          bundle config set path 'vendor/bundle'
          bundle config set without 'development test'
          bundle --version

      - name: Install Ruby gems
        run: |
          bundle install --jobs 4 --retry 3 --verbose

      - name: Configure SSH for match (if key present)
        run: |
          if [ -n "${{ secrets.MATCH_DEPLOY_KEY }}" ]; then
            mkdir -p ~/.ssh
            echo "${{ secrets.MATCH_DEPLOY_KEY }}" > ~/.ssh/match_deploy_key
            chmod 600 ~/.ssh/match_deploy_key
            printf "%s\n" \
              "Host github.com" \
              "  IdentityFile ~/.ssh/match_deploy_key" \
              "  StrictHostKeyChecking no" > ~/.ssh/config
            chmod 600 ~/.ssh/config
          fi

      - name: Build & Upload (Fastlane)
        env:
          GITHUB_REPOSITORY:   ${{ github.repository }}
          MATCH_REPOSITORY:    ${{ secrets.MATCH_REPOSITORY }}
          MATCH_PASSWORD:      ${{ secrets.MATCH_PASSWORD }}
          APPSTORE_ISSUER_ID:  ${{ secrets.APPSTORE_ISSUER_ID }}
          APPSTORE_KEY_ID:     ${{ secrets.APPSTORE_KEY_ID }}
          APPSTORE_P8:         ${{ secrets.APPSTORE_P8 }}
          IOS_BUNDLE_ID:       ${{ secrets.IOS_BUNDLE_ID }}
          PROJECT_NAME:        ${{ secrets.PROJECT_NAME }}
          IOS_SCHEME:          ${{ secrets.IOS_SCHEME }}
          # ВАЖНО: build работает ТОЛЬКО в readonly (не создаёт новые сертификаты)
          #STRICT_CERTS:        "1"
        run: |
          bundle exec fastlane ios build_ios
