name: Generate iOS Certs
on: { workflow_dispatch: {} }
jobs:
  certs:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: false
      - name: Prepare bundler (arm64-safe)
        run: |
          gem install bundler -v ">=2.5.0"
          bundle config set force_ruby_platform true
          if [ -f Gemfile.lock ]; then
            bundle lock --add-platform ruby || true
            bundle lock --add-platform arm64-darwin-23 || true
            bundle lock --add-platform x86_64-darwin-23 || true
          fi
      - name: Bundle install
        run: bundle install --path vendor/bundle --jobs 4 --retry 3
      - name: Sync certs (write mode)
        env:
          APPSTORE_ISSUER_ID: ${{ secrets.APPSTORE_ISSUER_ID }}
          APPSTORE_KEY_ID:     ${{ secrets.APPSTORE_KEY_ID }}
          APPSTORE_P8:         ${{ secrets.APPSTORE_P8 }}
          IOS_BUNDLE_ID:       ${{ secrets.IOS_BUNDLE_ID }}
          MATCH_GIT_URL:       https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ secrets.MATCH_REPOSITORY }}.git
          MATCH_GIT_BRANCH:    main
          MATCH_PASSWORD:      ${{ secrets.MATCH_PASSWORD }}
          MATCH_READONLY:      "false"
        run: bundle exec fastlane ios sync_certificates
