name: Generate iOS Certificates

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Configure SSH for match
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.MATCH_DEPLOY_KEY }}" > ~/.ssh/match_deploy_key
          chmod 600 ~/.ssh/match_deploy_key
          printf "%s\n" \
            "Host github.com" \
            "  IdentityFile ~/.ssh/match_deploy_key" \
            "  StrictHostKeyChecking no" > ~/.ssh/config
          chmod 600 ~/.ssh/config

      - name: Run Fastlane generate_certs
        env:
          APPSTORE_ISSUER_ID:  ${{ secrets.APPSTORE_ISSUER_ID }}
          APPSTORE_KEY_ID:     ${{ secrets.APPSTORE_KEY_ID }}
          APPSTORE_P8:         ${{ secrets.APPSTORE_P8 }}
          IOS_BUNDLE_ID:       ${{ secrets.IOS_BUNDLE_ID }}
          GH_PAT:              ${{ secrets.GH_PAT }}
          GITHUB_REPOSITORY:   ${{ github.repository }}
          MATCH_REPOSITORY:    ${{ secrets.MATCH_REPOSITORY }}
          MATCH_PASSWORD:      ${{ secrets.MATCH_PASSWORD }}
        run: |
          bundle install
          bundle exec fastlane ios generate_certs
