name: iOS One-Time Setup (native)

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: false

      - name: Prepare bundler
        run: |
          gem install bundler -v 2.7.2
          bundle config set path 'vendor/bundle'
          bundle config set without 'development test'
          bundle --version

      - name: Install Ruby gems
        run: |
          bundle install --jobs 4 --retry 3 --verbose

      - name: Fastlane setup_ci_integration (auto creates deploy key)
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          MATCH_REPOSITORY: ${{ secrets.MATCH_REPOSITORY }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          APPSTORE_ISSUER_ID: ${{ secrets.APPSTORE_ISSUER_ID }}
          APPSTORE_KEY_ID: ${{ secrets.APPSTORE_KEY_ID }}
          APPSTORE_P8: ${{ secrets.APPSTORE_P8 }}
        run: |
          bundle exec fastlane ios setup_ci_integration
