name: Generate iOS Certificates (native)
on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: macos-latest
    env:
      MATCH_DEPLOY_KEY: ${{ secrets.MATCH_DEPLOY_KEY }}  # как в CI_Core
    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: SSH agent + add MATCH_DEPLOY_KEY (как в CI_Core)
        if: ${{ env.MATCH_DEPLOY_KEY != '' }}
        shell: bash
        run: |
          eval "$(ssh-agent -s)"
          ssh-add - <<< "${MATCH_DEPLOY_KEY}"
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Fastlane
        env:
          APPSTORE_ISSUER_ID:  ${{ secrets.APPSTORE_ISSUER_ID }}
          APPSTORE_KEY_ID:     ${{ secrets.APPSTORE_KEY_ID }}
          APPSTORE_P8:         ${{ secrets.APPSTORE_P8 }}
          IOS_BUNDLE_ID:       ${{ secrets.IOS_BUNDLE_ID }}
          MATCH_REPOSITORY:    ${{ secrets.MATCH_REPOSITORY }}   # org/repo
          MATCH_PASSWORD:      ${{ secrets.MATCH_PASSWORD }}
        run: |
          bundle exec fastlane ios sync_certificates
