\
        name: Build iOS (Native, SPM) & TestFlight

        on:
          push:
            branches: [ main ]
            paths:
              - 'fastlane/**'
              - '.github/workflows/ios_build_native_spm.yml'
              - '*.xcodeproj/**'
              - '*.xcodeproj'
              - '**/*.swift'
              - 'Package.resolved'
              - 'Package.swift'
          workflow_dispatch:

        jobs:
          certs:
            runs-on: macos-latest
            steps:
              - uses: actions/checkout@v4

              - name: Setup Ruby & Bundler
                uses: ruby/setup-ruby@v1
                with:
                  ruby-version: '3.2'
                  bundler-cache: true

              - name: Install gems
                run: bundle install --path vendor/bundle

              - name: Add match SSH deploy key
                shell: bash
                run: |
                  mkdir -p ~/.ssh
                  echo "$MATCH_DEPLOY_KEY" > ~/.ssh/id_rsa
                  chmod 600 ~/.ssh/id_rsa
                  ssh-keyscan github.com >> ~/.ssh/known_hosts
                  eval "$(ssh-agent -s)"
                  ssh-add ~/.ssh/id_rsa
                env:
                  MATCH_DEPLOY_KEY: ${{ secrets.MATCH_DEPLOY_KEY }}

              - name: Sync certs & profiles (match)
                run: bundle exec fastlane ios sync_certificates
                env:
                  APPSTORE_ISSUER_ID: ${{ secrets.APPSTORE_ISSUER_ID }}
                  APPSTORE_KEY_ID: ${{ secrets.APPSTORE_KEY_ID }}
                  APPSTORE_P8: ${{ secrets.APPSTORE_P8 }}
                  IOS_BUNDLE_ID: ${{ secrets.IOS_BUNDLE_ID }}
                  MATCH_REPOSITORY: ${{ secrets.MATCH_REPOSITORY }}
                  MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}

          build:
            runs-on: macos-latest
            needs: certs
            env:
              # Repo variables: rename project/scheme without editing code
              XCODEPROJ_NAME: ChickCare
              SCHEME: ChickenCare
            steps:
              - uses: actions/checkout@v4

              - name: Cache SwiftPM
                uses: actions/cache@v4
                with:
                  path: |
                    ~/Library/Developer/Xcode/DerivedData
                    ~/Library/Caches/org.swift.swiftpm
                    ~/.swiftpm
                  key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
                  restore-keys: |
                    ${{ runner.os }}-spm-

              - name: Setup Ruby & Bundler
                uses: ruby/setup-ruby@v1
                with:
                  ruby-version: '3.2'
                  bundler-cache: true

              - name: Install gems
                run: bundle install --path vendor/bundle

              - name: Resolve SPM
                run: bundle exec fastlane ios resolve_spm

              - name: Build .ipa
                run: bundle exec fastlane ios build

          upload:
            runs-on: macos-latest
            needs: build
            steps:
              - uses: actions/checkout@v4

              - name: Setup Ruby & Bundler
                uses: ruby/setup-ruby@v1
                with:
                  ruby-version: '3.2'
                  bundler-cache: true

              - name: Install gems
                run: bundle install --path vendor/bundle

              - name: Upload to TestFlight
                run: bundle exec fastlane ios upload_beta
                env:
                  APPSTORE_ISSUER_ID: ${{ secrets.APPSTORE_ISSUER_ID }}
                  APPSTORE_KEY_ID: ${{ secrets.APPSTORE_KEY_ID }}
                  APPSTORE_P8: ${{ secrets.APPSTORE_P8 }}
                  IOS_BUNDLE_ID: ${{ secrets.IOS_BUNDLE_ID }}
