name: main (Build IOS)
on: { workflow_dispatch: {} }
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true
      - name: Install gems
        run: bundle install --path vendor/bundle
      - name: Build + Upload (init_ci)
        env:
          APPSTORE_ISSUER_ID: ${{ secrets.APPSTORE_ISSUER_ID }}
          APPSTORE_KEY_ID:     ${{ secrets.APPSTORE_KEY_ID }}
          APPSTORE_P8:         ${{ secrets.APPSTORE_P8 }}
          IOS_BUNDLE_ID:       ${{ secrets.IOS_BUNDLE_ID }}
          MATCH_GIT_URL:       https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ secrets.MATCH_REPOSITORY }}.git
          MATCH_GIT_BRANCH:    main
          MATCH_PASSWORD:      ${{ secrets.MATCH_PASSWORD }}
          MATCH_READONLY:      "true"
          PROJECT_NAME:        ${{ secrets.PROJECT_NAME }}
          IOS_SCHEME:          ${{ secrets.IOS_SCHEME }}
        run: bundle exec fastlane ios init_ci
